#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKSPACE_ROOT="$(cd "$REPO_ROOT/.." && pwd)"
SHARED_ZLAB_ROOT="${ZLAB_WORKSPACE_ROOT:-$WORKSPACE_ROOT/zlab}"

if [[ ! -f "$SHARED_ZLAB_ROOT/env/defaults.sh" ]]; then
  echo "Shared workspace zlab was not found at: $SHARED_ZLAB_ROOT" >&2
  exit 1
fi

if [[ -f "$REPO_ROOT/zlab/ab_env.sh" ]]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/zlab/ab_env.sh"
fi

# shellcheck disable=SC1091
source "$SHARED_ZLAB_ROOT/env/defaults.sh"

export ZLAB_KRONOS_REPO="$REPO_ROOT"
export ZLAB_KRONOS_PYTHON="${PYTHON_BIN:-$ZLAB_KRONOS_PYTHON}"
export ZLAB_DATA_ROOT="${KRONOS_LOCAL_CSV_DIR:-$ZLAB_DATA_ROOT}"
export ZLAB_CONTEXTS="${KRONOS_CONTEXTS:-${KRONOS_LOOKBACK_WINDOW:-$ZLAB_CONTEXTS}}"
export ZLAB_HORIZONS="${KRONOS_HORIZONS:-$ZLAB_HORIZONS}"
export ZLAB_SPLIT_MODE="${EVAL_MODE:-$ZLAB_SPLIT_MODE}"
export ZLAB_KRONOS_ZERO_SHOT_ROOT="${ZERO_SHOT_ROOT:-${STAGE1_ROOT:-$ZLAB_KRONOS_ZERO_SHOT_ROOT}}"
export ZLAB_KRONOS_DEVICE="${DEVICE:-$ZLAB_KRONOS_DEVICE}"
export ZLAB_KRONOS_SAMPLE_COUNT="${KRONOS_INFERENCE_SAMPLE_COUNT:-$ZLAB_KRONOS_SAMPLE_COUNT}"
export ZLAB_KRONOS_TEMPERATURE="${KRONOS_INFERENCE_T:-$ZLAB_KRONOS_TEMPERATURE}"
export ZLAB_KRONOS_TOP_P="${KRONOS_INFERENCE_TOP_P:-$ZLAB_KRONOS_TOP_P}"
export ZLAB_KRONOS_TOP_K="${KRONOS_INFERENCE_TOP_K:-$ZLAB_KRONOS_TOP_K}"
export ZLAB_KRONOS_EVAL_BATCH_SIZE="${KRONOS_EVAL_BATCH_SIZE:-$ZLAB_KRONOS_EVAL_BATCH_SIZE}"
export ZLAB_KRONOS_TOKENIZER_PATH="${KRONOS_PRETRAINED_TOKENIZER_PATH:-$ZLAB_KRONOS_TOKENIZER_PATH}"
export ZLAB_KRONOS_MODEL_PATH="${KRONOS_PRETRAINED_PREDICTOR_PATH:-$ZLAB_KRONOS_MODEL_PATH}"

"$SHARED_ZLAB_ROOT/scripts/run_kronos_zero_shot.sh" "$@"
